In [4]:
import numpy as np
import matplotlib.pyplot as plt
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]#肿瘤的大小和时间
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]#是否为恶性肿瘤

In [5]:
X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)#构建训练集

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [8]:
kNN_classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=6, p=2,
           weights='uniform')

In [11]:
x = np.array([8.093607318, 3.365731514])#等待判断的肿瘤
kNN_classifier.predict(x)

C:\Users\SilentY\Anaconda3\lib\site-packages\sklearn\utils\validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([1])

In [12]:
X_predict = x.reshape(1,-1)

In [13]:
X_predict

array([[ 8.09360732,  3.36573151]])

In [15]:
kNN_classifier.predict(X_predict)

array([1])

In [16]:
y_predict = kNN_classifier.predict(X_predict)

In [19]:
y_predict[0]

1