In [16]:
import numpy as np
A = np.loadtxt(open("D:/Work/数据挖掘ML/回归分析/randn_data_regression_A.csv","rb"),delimiter=",",skiprows=0) 
B = np.loadtxt(open("D:/Work/数据挖掘ML/回归分析/randn_data_regression_B.csv","rb"),delimiter=",",skiprows=0) 
new_A = np.hstack([np.ones((len(A), 1)),A])

In [17]:
new_A

array([[ 1.        , -0.43256481, -1.01063371, ...,  0.52434007,
        -0.78793113,  0.60358953],
       [ 1.        , -1.66558438,  0.61446305, ..., -0.1933223 ,
        -0.02022444, -1.27698055],
       [ 1.        ,  0.12533231,  0.50774078, ...,  0.07251873,
        -0.7443348 ,  1.05665513],
       ..., 
       [ 1.        , -0.92190162,  0.56896065, ..., -1.47215039,
         0.31523604, -0.05946208],
       [ 1.        , -2.17067449, -0.82171429, ..., -1.40166474,
         2.57047553, -2.09209424],
       [ 1.        , -0.05918782, -0.26560685, ...,  1.03986473,
        -0.26376483, -1.36321714]])

In [18]:

y = x * 3. + 4. + np.random.normal(size=100)

In [21]:
y.shape

(100,)

In [22]:
B.shape

(50,)

In [23]:

x = 2 * np.random.random(size=100)
x.shape

(100,)

In [24]:
A.shape

(50, 500)

In [26]:
def J(theta, X_b, y):
    try:
        return np.sum((y - X_b.dot(theta))**2) / len(X_b)
    except:
        return float('inf')

def dJ(theta, X_b, y):
    res = np.empty(len(theta))
    res[0] = np.sum(X_b.dot(theta) - y)
    
    for i in range(1, len(theta)):
        res[i] = (X_b.dot(theta) - y).dot(X_b[:,i])
    
    return res * 2 / len(X_b) # 对于一个二维数组，len返回其行数


def dJ(theta, X_b, y):
    res = np.empty(len(theta))
    res[0] = np.sum(X_b.dot(theta) - y)
    
    for i in range(1, len(theta)):
        res[i] = (X_b.dot(theta) - y).dot(X_b[:,i])
    
    return res * 2 / len(X_b) # 对于一个二维数组，len返回其行数
 
def gradient_descent(X_b, y, initial_theta, eta, n_iters = 1e4, epsilon=1e-8):  
    theta = initial_theta
    i_iter = 0
    
    while i_iter < n_iters:
        gradient = dJ(theta, X_b, y)
        last_theta = theta
        theta = theta - eta*gradient
        
        if(abs(J(theta, X_b, y) - J(last_theta, X_b, y)) < epsilon):
            break
            
        i_iter += 1
        
    return theta

In [27]:
X_b = np.hstack([np.ones((len(x), 1)) , x.reshape(-1, 1)])
initial_theta = np.zeros(X_b.shape[1])  # 每个特征对应一个theta，（还应再多一个theta0）
eta = 0.01

In [29]:
X_b.shape

(100, 2)

In [30]:
X_b

array([[ 1.        ,  0.10688214],
       [ 1.        ,  1.72774154],
       [ 1.        ,  1.11370294],
       [ 1.        ,  0.24456478],
       [ 1.        ,  1.05831136],
       [ 1.        ,  0.85469924],
       [ 1.        ,  0.11514827],
       [ 1.        ,  1.4142436 ],
       [ 1.        ,  1.79535934],
       [ 1.        ,  0.21199444],
       [ 1.        ,  1.59426152],
       [ 1.        ,  0.48813346],
       [ 1.        ,  1.47588526],
       [ 1.        ,  1.68450598],
       [ 1.        ,  1.05377753],
       [ 1.        ,  0.98242078],
       [ 1.        ,  1.85656948],
       [ 1.        ,  1.82185621],
       [ 1.        ,  0.16466322],
       [ 1.        ,  1.16371578],
       [ 1.        ,  0.42627996],
       [ 1.        ,  1.86273142],
       [ 1.        ,  0.86336399],
       [ 1.        ,  1.9434233 ],
       [ 1.        ,  0.18064009],
       [ 1.        ,  1.84975672],
       [ 1.        ,  0.91300263],
       [ 1.        ,  0.04048594],
       [ 1.        ,

In [31]:
x

array([ 0.10688214,  1.72774154,  1.11370294,  0.24456478,  1.05831136,
        0.85469924,  0.11514827,  1.4142436 ,  1.79535934,  0.21199444,
        1.59426152,  0.48813346,  1.47588526,  1.68450598,  1.05377753,
        0.98242078,  1.85656948,  1.82185621,  0.16466322,  1.16371578,
        0.42627996,  1.86273142,  0.86336399,  1.9434233 ,  0.18064009,
        1.84975672,  0.91300263,  0.04048594,  1.1324151 ,  0.60866741,
        1.0174461 ,  1.73829685,  1.44860577,  1.0805554 ,  1.02047382,
        1.02171424,  0.58863048,  0.11610882,  0.16155233,  1.36830036,
        0.04722726,  1.15892628,  0.12572655,  0.09303059,  1.13183752,
        0.7909618 ,  1.41088612,  1.92528117,  0.67941431,  0.65930952,
        0.32736463,  1.84931597,  0.47770332,  0.91498616,  1.1635364 ,
        1.46184   ,  0.71927887,  1.96776711,  0.67048029,  1.94875881,
        0.57720071,  1.89641974,  0.98173236,  1.66992415,  1.02620038,
        1.84653094,  1.21613968,  0.87507255,  0.60646409,  1.83

In [32]:
A

array([[-0.43256481, -1.01063371, -1.18777702, ...,  0.52434007,
        -0.78793113,  0.60358953],
       [-1.66558438,  0.61446305, -2.20232072, ..., -0.1933223 ,
        -0.02022444, -1.27698055],
       [ 0.12533231,  0.50774078,  0.98633739, ...,  0.07251873,
        -0.7443348 ,  1.05665513],
       ..., 
       [-0.92190162,  0.56896065,  0.66302415, ..., -1.47215039,
         0.31523604, -0.05946208],
       [-2.17067449, -0.82171429, -0.85419737, ..., -1.40166474,
         2.57047553, -2.09209424],
       [-0.05918782, -0.26560685, -1.20131481, ...,  1.03986473,
        -0.26376483, -1.36321714]])

In [33]:
B

array([ 23.89339009,  33.20144177,  22.39949468, -19.32394772,
        12.39437962,  20.10064196,   0.9475577 ,   4.09406054,
        -9.50853573, -17.03670172,  -2.96642551, -52.73477252,
         7.73314133,  -9.96402129, -34.03835236,   8.65976176,
        25.18207416,   2.07394014, -23.13220439,  22.2200929 ,
        31.45289019,   8.058077  ,  33.78267268,  -8.97703724,
        13.89145506, -30.88725862,  32.95478377, -17.38744779,
       -27.43849988, -34.10177735,  -4.74377605,  15.28627332,
         8.8290119 ,  31.65051561,  11.62801114,  -2.78917528,
        12.2897169 ,  26.20282182,   3.97459607, -40.40049502,
        -2.73051159,  -6.97576125,   9.85297381,  40.14957363,
        65.94806795, -37.09512644,  28.93738712, -23.10672354,
       -12.04447767,  22.97877143])

In [34]:
y

array([  9.70432388,   7.46870964,   8.65114719,   6.30298286,
         5.44359184,   5.68160979,   8.86259587,   9.57707782,
         5.9218112 ,   5.13268544,   8.07588948,  10.26992086,
         9.57870098,   9.77652904,   9.91207787,   8.3477229 ,
         8.91524474,   8.54517894,   9.44688187,   6.53110797,
         4.50777741,   8.45905586,   4.21713108,   6.24581727,
         9.66524245,   5.88990825,   9.70346117,   5.98118473,
         6.54154086,   4.32661007,   2.90619285,   8.15757412,
         4.05976169,   8.02953798,   5.58274105,   4.70579869,
         6.14702716,   9.62621242,   6.58172439,   7.94602231,
         5.95372451,  10.43684555,   5.22130277,   5.60218767,
         8.17028045,   3.47066476,   6.10207832,   4.71189597,
         9.04355616,   8.68486587,   6.2971807 ,   6.95633674,
         6.87194777,   6.00707464,   7.1444301 ,   6.85331906,
        10.69347814,   5.42284308,   5.78775042,   5.51289258,
         7.58306767,   8.80925014,   6.13260204,   9.66

In [38]:
X_b = np.hstack([np.ones((len(A), 1)) ,A])

In [40]:
X_b.shape

(50, 501)