In [1]:
import numpy as np
A = np.loadtxt(open("D:/Work/数据挖掘ML/回归分析/randn_data_regression_A.csv","rb"),delimiter=",",skiprows=0) 
B = np.loadtxt(open("D:/Work/数据挖掘ML/回归分析/randn_data_regression_B.csv","rb"),delimiter=",",skiprows=0) 
new_A = np.hstack([A,np.ones((len(A),1))])
A = np.matrix(A)
B = np.matrix(B)
new_A = np.matrix(new_A)

def J(theta, X_b, y):
    try:
        return np.sum((y - X_b.dot(theta))**2) / len(X_b)
    except:
        return float('inf')

def dJ(theta, X_b, y):
    res = np.empty(len(theta))
    res[0] = np.sum(X_b.dot(theta) - y)
    
    for i in range(1, len(theta)):
        res[i] = (X_b.dot(theta) - y).dot(X_b[:,i])
    
    return res * 2 / len(X_b) # 对于一个二维数组，len返回其行数


def gradient_descent(X_b, y, initial_theta, eta, n_iters = 1e4, epsilon=1e-8):  
    theta = initial_theta
    i_iter = 0
    
    while i_iter < n_iters:
        gradient = dJ(theta, X_b, y)
        last_theta = theta
        theta = theta - eta*gradient
        
        if(abs(J(theta, X_b, y) - J(last_theta, X_b, y)) < epsilon):
            break
            
        i_iter += 1
        
    return theta

In [12]:
X_b = new_A
y = B.T
initial_theta = np.zeros(x_b.shape[1])
eta = 0.01

In [13]:
X_b.shape

(50, 501)

In [14]:
y.shape

(50, 1)

In [15]:
initial_theta.shape

(501,)

In [16]:
eta

0.01

In [17]:
n_iters = 1e4
epsilon=1e-8

In [18]:
theta = initial_theta
i_iter = 0

In [21]:
res = np.empty(len(theta))
res[0] = np.sum(X_b.dot(theta) - y)

In [22]:
res

array([ -8.16922735e+003,   9.36909536e-312,               nan,
         0.00000000e+000,   9.33581101e-315,   2.47032823e-321,
         9.36919855e-312,   9.36919855e-312,   9.36919849e-312,
         9.36919849e-312,   9.36919849e-312,   9.36919849e-312,
         9.36919849e-312,   9.36919849e-312,   9.36919849e-312,
         9.36919849e-312,   9.36919849e-312,   9.36919849e-312,
         9.36919849e-312,   9.36919849e-312,   9.36919849e-312,
         9.36919849e-312,   9.36919849e-312,   9.36919849e-312,
         9.36919849e-312,   9.36919849e-312,   9.36919849e-312,
         9.36919849e-312,   9.36919849e-312,   9.36919849e-312,
         9.36919849e-312,   9.36919849e-312,   9.36919849e-312,
         9.36919849e-312,   9.36919849e-312,   9.36919849e-312,
         9.36919849e-312,   9.36919849e-312,   9.36919849e-312,
         9.36919849e-312,   9.36919849e-312,   9.36919849e-312,
         9.36919849e-312,   9.36919849e-312,   9.36919849e-312,
         9.36919850e-312,   9.36919850e-

In [24]:
res[0]

-8169.22735345

In [25]:
len(theta)

501

In [26]:
 res[1] = (X_b.dot(theta) - y).dot(X_b[:,1])

ValueError: setting an array element with a sequence.

In [27]:
X_b[:,1]

matrix([[ -1.01063371e+00],
        [  6.14463049e-01],
        [  5.07740785e-01],
        [  1.69242987e+00],
        [  5.91282587e-01],
        [ -6.43595203e-01],
        [  3.80337252e-01],
        [ -1.00911552e+00],
        [ -1.95106700e-02],
        [ -4.82207890e-02],
        [  4.32000000e-05],
        [ -3.17859451e-01],
        [  1.09500374e+00],
        [ -1.87399026e+00],
        [  4.28183273e-01],
        [  8.95638471e-01],
        [  7.30957338e-01],
        [  5.77857346e-01],
        [  4.03140320e-02],
        [  6.77089188e-01],
        [  5.68900205e-01],
        [ -2.55645416e-01],
        [ -3.77468956e-01],
        [ -2.95887110e-01],
        [ -1.47513451e+00],
        [ -2.34004048e-01],
        [  1.18444837e-01],
        [  3.14809043e-01],
        [  1.44350824e+00],
        [ -3.50974738e-01],
        [  6.23233851e-01],
        [  7.99048618e-01],
        [  9.40889941e-01],
        [ -9.92091736e-01],
        [  2.12035152e-01],
        [  2.3788207

In [28]:
X_b

matrix([[-0.43256481, -1.01063371, -1.18777702, ..., -0.78793113,
          0.60358953,  1.        ],
        [-1.66558438,  0.61446305, -2.20232072, ..., -0.02022444,
         -1.27698055,  1.        ],
        [ 0.12533231,  0.50774078,  0.98633739, ..., -0.7443348 ,
          1.05665513,  1.        ],
        ..., 
        [-0.92190162,  0.56896065,  0.66302415, ...,  0.31523604,
         -0.05946208,  1.        ],
        [-2.17067449, -0.82171429, -0.85419737, ...,  2.57047553,
         -2.09209424,  1.        ],
        [-0.05918782, -0.26560685, -1.20131481, ..., -0.26376483,
         -1.36321714,  1.        ]])