In [96]:
import numpy as np
from scipy.linalg import solve
A = np.loadtxt(open("D:/Work/数据挖掘ML/回归分析/randn_data_regression_A.csv","rb"),delimiter=",",skiprows=0) 
B = np.loadtxt(open("D:/Work/数据挖掘ML/回归分析/randn_data_regression_B.csv","rb"),delimiter=",",skiprows=0) 
new_A = np.hstack([A,np.ones((len(A),1))])
A = np.matrix(A)
B = np.matrix(B)
new_A = np.matrix(new_A)

a = np.array([[3, 1, -2], [1, -1, 4], [2, 0, 3]])
b = np.array([5, -2, 2.5])
a = np.matrix(a)
b = np.matrix(b)

In [97]:
type(a)

numpy.matrixlib.defmatrix.matrix

In [98]:
type(A)

numpy.matrixlib.defmatrix.matrix

In [99]:
def linerRegression(X_train,Y_train):
    theta = np.linalg.inv(X_train.T.dot(X_train)).dot(X_train.T.dot(Y_train.T))
    return theta

In [100]:
x = linerRegression(a,b)

In [101]:
x

matrix([[ 0.5],
        [ 4.5],
        [ 0.5]])

In [102]:
a

matrix([[ 3,  1, -2],
        [ 1, -1,  4],
        [ 2,  0,  3]])

In [103]:
a.dot(x)

matrix([[ 5. ],
        [-2. ],
        [ 2.5]])

In [104]:
b

matrix([[ 5. , -2. ,  2.5]])

In [105]:
A.shape

(50, 500)

In [106]:
B.shape

(1, 50)

In [107]:
a.shape

(3, 3)

In [108]:
b.shape

(1, 3)

In [109]:
t = linerRegression(A,B)

In [111]:
A.dot(t)

matrix([[   21.57704474],
        [-1961.99703526],
        [ 1888.58078904],
        [ 1609.83439033],
        [-3823.71187289],
        [ 1493.61364605],
        [-1695.2699205 ],
        [-1787.20214384],
        [  504.99866558],
        [ -356.46656061],
        [  261.01283771],
        [-2243.18973101],
        [-4192.9603175 ],
        [ 1654.88209704],
        [  346.12838559],
        [ -183.83333494],
        [-3175.87712617],
        [ 3002.43321263],
        [-3938.88860752],
        [ 2000.74418315],
        [-2399.66404817],
        [   42.35407197],
        [  465.71800052],
        [ 2544.9259943 ],
        [-4744.07659653],
        [ 2655.86688546],
        [ 1508.05111887],
        [  852.03766358],
        [ -258.83116799],
        [ -742.25443041],
        [ 4781.12641507],
        [  255.74494819],
        [ -456.86919056],
        [ 6043.35814488],
        [ 2085.99069248],
        [ 1514.80480592],
        [ 1548.65012981],
        [-5492.30866108],
        [ 13

In [112]:
z = linerRegression(new_A, B)

In [115]:
new_A.dot(z)

matrix([[ -5027.82579442],
        [ 26322.82740133],
        [ -6648.28950894],
        [ 13435.66369512],
        [  6801.70831172],
        [  1167.66721153],
        [ 10057.77164319],
        [ 12059.00200176],
        [-10964.36584345],
        [-10538.28538152],
        [-37361.38968832],
        [-47868.379179  ],
        [-10353.30872016],
        [ -4264.72377071],
        [ 24349.95224111],
        [ 34818.37956994],
        [ 38260.12394973],
        [ 14993.20460123],
        [ 25443.04707584],
        [ 26615.80788523],
        [  -792.62987741],
        [  -365.19905481],
        [ 24008.19176671],
        [ 16998.04228389],
        [ 21790.24779775],
        [ 44907.98321145],
        [ 30724.22272979],
        [ 50816.02057189],
        [-26981.34305269],
        [-28685.89771946],
        [ 25580.65365335],
        [ 10276.30511427],
        [-23135.8619946 ],
        [  -506.54158622],
        [-11338.31196349],
        [  8737.78493251],
        [ 45592.55189843],
 