In [1]:
# coding:utf-8
import numpy as np 
class NeuralNetwork(): 
    # 随机初始化权重
    def __init__(self): 
        np.random.seed(1) 
        self.synaptic_weights = 2 * np.random.random((400,1)) - 1 
    
    # 定义激活函数：这里使用sigmoid
    def sigmoid(self, x):  
        return 1 / (1 + np.exp(-x)) 
    
    # 训练模型 
    def train(self, training_inputs, training_outputs,learn_rate, training_iterations): 
        # 迭代训练
        for iteration in range(training_iterations): 
            #前向计算 
            output = self.think(training_inputs) 
            # 计算误差 
            error = training_outputs - output 
    
    def think(self, inputs): 
        # 输入通过网络得到输出 
        # 转化为浮点型数据类型 
        inputs = inputs.astype(float) 
        output = self.sigmoid(np.dot(inputs, self.synaptic_weights)) 
        return output 

In [2]:
import pandas as pd

In [3]:
X = pd.read_csv("X_data.csv",header=None)

In [5]:
y = pd.read_csv("y_label.csv",header=None)

In [7]:
neural_network = NeuralNetwork() 
print("随机初始化的权重矩阵W")
print(neural_network.synaptic_weights)

随机初始化的权重矩阵W
[[ -1.65955991e-01]
 [  4.40648987e-01]
 [ -9.99771250e-01]
 [ -3.95334855e-01]
 [ -7.06488218e-01]
 [ -8.15322810e-01]
 [ -6.27479577e-01]
 [ -3.08878546e-01]
 [ -2.06465052e-01]
 [  7.76334680e-02]
 [ -1.61610971e-01]
 [  3.70439001e-01]
 [ -5.91095501e-01]
 [  7.56234873e-01]
 [ -9.45224814e-01]
 [  3.40935020e-01]
 [ -1.65390395e-01]
 [  1.17379657e-01]
 [ -7.19226123e-01]
 [ -6.03797022e-01]
 [  6.01489137e-01]
 [  9.36523151e-01]
 [ -3.73151644e-01]
 [  3.84645231e-01]
 [  7.52778305e-01]
 [  7.89213327e-01]
 [ -8.29911577e-01]
 [ -9.21890434e-01]
 [ -6.60339161e-01]
 [  7.56285007e-01]
 [ -8.03306332e-01]
 [ -1.57784750e-01]
 [  9.15779060e-01]
 [  6.63305699e-02]
 [  3.83754228e-01]
 [ -3.68968738e-01]
 [  3.73001855e-01]
 [  6.69251344e-01]
 [ -9.63423445e-01]
 [  5.00288630e-01]
 [  9.77722178e-01]
 [  4.96331309e-01]
 [ -4.39112016e-01]
 [  5.78558657e-01]
 [ -7.93547987e-01]
 [ -1.04212948e-01]
 [  8.17191006e-01]
 [ -4.12771703e-01]
 [ -4.24449323e-01]
 [ -7.39

In [8]:
train_data=X
training_inputs = np.array(train_data) 

In [10]:
training_outputs = np.array(y)

In [11]:
training_outputs

array([[10],
       [10],
       [10],
       ..., 
       [ 9],
       [ 9],
       [ 9]], dtype=int64)

In [12]:
# 参数学习率
learn_rate=0.1
# 模型迭代的次数
epoch=1500
neural_network.train(training_inputs, training_outputs, learn_rate, epoch) 
print("迭代计算之后权重矩阵W: ")
print(neural_network.synaptic_weights)

迭代计算之后权重矩阵W: 
[[ -1.65955991e-01]
 [  4.40648987e-01]
 [ -9.99771250e-01]
 [ -3.95334855e-01]
 [ -7.06488218e-01]
 [ -8.15322810e-01]
 [ -6.27479577e-01]
 [ -3.08878546e-01]
 [ -2.06465052e-01]
 [  7.76334680e-02]
 [ -1.61610971e-01]
 [  3.70439001e-01]
 [ -5.91095501e-01]
 [  7.56234873e-01]
 [ -9.45224814e-01]
 [  3.40935020e-01]
 [ -1.65390395e-01]
 [  1.17379657e-01]
 [ -7.19226123e-01]
 [ -6.03797022e-01]
 [  6.01489137e-01]
 [  9.36523151e-01]
 [ -3.73151644e-01]
 [  3.84645231e-01]
 [  7.52778305e-01]
 [  7.89213327e-01]
 [ -8.29911577e-01]
 [ -9.21890434e-01]
 [ -6.60339161e-01]
 [  7.56285007e-01]
 [ -8.03306332e-01]
 [ -1.57784750e-01]
 [  9.15779060e-01]
 [  6.63305699e-02]
 [  3.83754228e-01]
 [ -3.68968738e-01]
 [  3.73001855e-01]
 [  6.69251344e-01]
 [ -9.63423445e-01]
 [  5.00288630e-01]
 [  9.77722178e-01]
 [  4.96331309e-01]
 [ -4.39112016e-01]
 [  5.78558657e-01]
 [ -7.93547987e-01]
 [ -1.04212948e-01]
 [  8.17191006e-01]
 [ -4.12771703e-01]
 [ -4.24449323e-01]
 [ -7.

In [13]:
neural_network.synaptic_weights.shape

(400, 1)

In [14]:
training_inputs.shape

(5000, 400)