In [1]:
import pandas as pd
import numpy as np

In [2]:
X = pd.read_csv("X_data.csv",header=None)
y = pd.read_csv("y_label.csv",header=None)

In [3]:
def sigmoid(x):  
    return 1 / (1 + np.exp(-x)) 

In [4]:
#计算Sigmoid函数的偏导数 
def sigmoid_derivative(x): 
    return x * (1 - x)

In [5]:
np.random.seed(1)
theta1 = np.random.randn(25,401)

In [6]:
theta2 = np.random.randn(10, 26)

In [7]:
def predictY(X,theta1,theta2):
    # theta1
    X = np.hstack([np.ones((len(X), 1)) , X])
    k = X.dot(theta1.T)
    k = sigmoid(k)

    # theta2
    k = np.hstack([np.ones((len(k), 1)) , k])
    k = k.dot(theta2.T)

    index = np.argmax(k,axis=1)
    index=index+1
    
    return index

In [8]:
result = predictY(X,theta1, theta2)

In [9]:
result

array([6, 7, 6, ..., 7, 6, 7], dtype=int64)

In [10]:
y_2 = []
for i in range(len(y)):
    y_2.append(y[0][i])

y = y_2
y = np.array(y)

In [11]:
y

array([10, 10, 10, ...,  9,  9,  9], dtype=int64)

In [12]:
error = y-result

In [13]:
error

array([4, 3, 4, ..., 2, 3, 2], dtype=int64)

In [14]:
adjustments = np.dot(X.T, error * sigmoid_derivative(result))

In [15]:
adjustments

array([  0.00000000e+00,   0.00000000e+00,   1.95181560e-01,
        -1.85346983e+00,  -2.32054710e-01,  -4.74510315e+00,
        -5.65888734e+00,   3.49981885e+01,   4.86901746e+00,
         3.08977736e+01,   1.04105232e+01,  -6.64323566e+00,
        -9.27601203e+00,  -1.49991224e+01,  -3.82145322e+01,
        -3.13378551e+01,  -1.00988921e+01,  -1.39308414e-01,
         1.11672792e-01,   0.00000000e+00,   1.03656000e-02,
         1.98758700e-02,  -2.05448826e+00,   4.47883565e+00,
        -1.96770979e+01,  -3.25263195e+01,  -1.16821735e+02,
        -6.62761569e+00,   4.52665036e+01,   1.15975857e+02,
         9.10429697e+01,   4.95368871e+01,  -9.49488042e-01,
        -1.19018404e+02,   3.90628517e+01,   7.95266950e+01,
         1.33405415e+01,  -2.08503975e+01,   2.05779828e-01,
         9.94103796e-01,  -8.89231980e-02,   4.85593722e-01,
        -1.50057779e+01,   1.33694468e+02,   7.05632506e+02,
         1.32309608e+03,   1.05016951e+03,   2.93808213e+02,
         3.02663795e+02,

In [18]:
theta11 = np.random.randn(25,401)+0.001
theta22 = np.random.randn(10, 26)+0.001

In [19]:
result2 = predictY(X,theta11, theta22)

In [20]:
error2 = y-result2

In [21]:
adjustments2 = np.dot(X.T, error2 * sigmoid_derivative(result2))

In [22]:
adjustments-adjustments2

array([  0.00000000e+00,   0.00000000e+00,   1.33219160e-01,
        -8.26880144e-01,  -5.27265067e+00,  -5.30404577e+01,
        -3.29943803e+00,   3.90653532e+01,  -5.90152029e+00,
        -9.72592939e+01,  -3.37046859e+01,   1.37399509e+01,
         1.44811237e+01,   7.31916406e+00,   1.44226337e+01,
         5.04279141e+00,   4.66368387e+00,   8.93486850e-01,
        -1.15247160e-01,   0.00000000e+00,   1.53016000e-02,
        -5.79967820e-02,  -2.20136500e+00,   5.35245246e+00,
         2.75200479e+01,   1.55730494e+01,   2.42611144e+01,
         8.60175615e+01,  -1.49508336e+02,  -3.70829683e+02,
        -2.72751314e+02,  -6.14617073e+01,  -2.91975594e+01,
         1.59045813e+02,   2.29488004e+02,   2.33011869e+02,
         4.45680277e+01,   7.79531240e+00,   8.67136912e-01,
         1.09458148e-01,  -1.31267578e-01,   7.17762994e-01,
        -8.29614118e+00,   1.47846733e+02,  -3.82760063e+01,
        -3.78389668e+02,  -3.70476686e+02,  -5.68023731e+01,
        -1.50608253e+02,